Repository chandannekya/Clean-Breath, pull requests merged in 2025-07, with the labels that each got.

#22 fix(security): Untrack .env file and add .env.example
  server/.env
  server/.env.example
Labels: gssoc25, level 1

#50 Improve SEO and accessibility in index.html
  index.html
Labels: gssoc25, level 3

#79 Fix UI/UX Issues Across Forms, Footer, FAQ, and Plant Page – Closes #73
  package-lock.json
  package.json
  src/App.jsx
  src/Component/Auth/Loginform.jsx
  src/Component/Auth/Signupform.jsx
  src/Component/Faq.jsx
  src/Component/FeatureCard.jsx
  src/Component/Footer.jsx
  src/Component/PlantCard.jsx
  src/Pages/AboutUs.jsx
  src/Pages/Feature.jsx
  src/Pages/HeroSection.jsx
  src/Pages/Login.jsx
  src/Pages/PlantDel.jsx
  src/Pages/SignUp.jsx
Labels: gssoc25, level 2
